name: Build Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Build Executable
      run: |
        pip install -r requirements.txt
        pyinstaller monitor.spec
        copy dist/GetPixy.exe GetPixy.exe
    
    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: GetPixy
        path: |
          GetPixy.exe
          monitor/
          monitor.cfg
          convert.cfg

