name: Build Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: pyinstaller monitor.spec

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: wledgetpixy
        path: |
          dist/wledgetpixy.exe
          monitor/
          monitor.cfg
          convert.cfg
          
